const GET_ALL_TASKS = "GET_ALL_TASKS";
const TOGGLE_COMPLETE_CHECKBOX = "TOGGLE_COMPLETE_CHECKBOX";
const SAVE_TASK = "SAVE_TASK";
const UPDATE_TASK = "UPDATE_TASK";
const SORT_TASKS = "SORT_TASKS";
const DELETE_TASK = "DELETE_TASK";

export {
  GET_ALL_TASKS,
  SAVE_TASK,
  TOGGLE_COMPLETE_CHECKBOX,
  UPDATE_TASK,
  DELETE_TASK,
  SORT_TASKS
};
